"use strict";

import type { Metadata } from "next";
import { Noto_Sans, Plus_Jakarta_Sans } from "next/font/google";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/utils/nextAuth/authOptions";
import { Toaster } from "@/shadcn/components/ui/toaster";
import { AppRootProvider } from "@/shared/appContainers";
import "./globals.css";

const notoSans = Noto_Sans({
    subsets: ["latin"],
    display: "swap",
    weight: '400'
})

export const plusJakartaSans = Plus_Jakarta_Sans({
    subsets: ["latin"],
    display: "swap",
    weight: '400'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) => {

    const session = await getServerSession(authOptions);

    return (
        <html lang="en">
            <body
                className={`${notoSans.className} ${plusJakartaSans.className} antialiased`}
            >
                <AppRootProvider session={session}>
                    {children}
                </AppRootProvider>
                <Toaster/>
            </body>
        </html>
    );
}

export default RootLayout;
